apps/finanzas/urls.py
from django.urls import path

from . import views

app_name = "app_finanzas"

urlpatterns = [
    #----------------------------- Departamentos ---------------------------
    path('departamentos/', views.Departamentos.as_view(), name='departamentos'),

    #---------------------------- Centro de Costos ----------------------
    path('centroDeCostos/', views.CentroDeCostos.as_view(), name='centroDeCostos'),
    path('crearCentroDeCostos/', views.CrearCentroDeCostos.as_view(), name='crearCentroDeCostos'),
    path('editarCentroDeCostos/', views.EditarCentroDeCostos.as_view(), name='editarCentroDeCostos'),
    #---------------------------- Proyectos ---------------------------
    path('proyectos/', views.Proyectos.as_view(), name='proyectos'),
    path('crearProyectos/', views.CrearProyectos.as_view(), name='crearProyectos'),
    path('editarProyectos/', views.EditarProyectos.as_view(), name='editarProyectos'),
    #----------------------------- Presupuestos de Centro de Costos -------------------------------
    path('presupuestosCDC/', views.PresupuestosCDC.as_view(), name='presupuestosCDC'),
    path('crearPresupuestosCDC/', views.CrearPresupuestosCDC.as_view(), name='crearPresupuestosCDC'),
    path('editarPresupuestosCDC/', views.EditarPresupuestosCDC.as_view(), name='editarPresupuestosCDC'),
    #----------------------------- Presupuestos de Proyectos --------------------------------------
    path('presupuestosP/', views.PresupuestosP.as_view(), name='presupuestosP'),
    path('crearPresupuestosP/', views.CrearPresupuestosP.as_view(), name='crearPresupuestosP'),
    path('editarPresupuestosP/', views.EditarPresupuestosP.as_view(), name='editarPresupuestosP'),

    #----------------------------- Compras --------------------------------------------------
    path('compra/', views.Compra.as_view(), name='compra'),
    path('crearCompra/', views.CrearCompra.as_view(), name='crearCompra'),
    path('editarCompra/', views.EditarCompra.as_view(), name='editarCompra'),
    #----------------------------- Cotizaciones --------------------------------------------------
    path('cotizacionesCompra/', views.CotizacionesCompra.as_view(), name='cotizacionesCompra'),
    path('crearCotizacionesCompra/', views.CrearCotizacionesCompra.as_view(), name='crearCotizacionesCompra'),
    path('editarCotizacionesCompra/', views.EditarCotizacionesCompra.as_view(), name='editarCotizacionesCompra'),
    #----------------------------- Ordenes de Compra --------------------------------------------------
    path('ordenesDeCompra/', views.OrdenesDeCompra.as_view(), name='ordenesDeCompra'),
    path('crearOrdenesDeCompra/', views.CrearOrdenesDeCompra.as_view(), name='crearOrdenesDeCompra'),
    path('editarOrdenesDeCompra/', views.EditarOrdenesDeCompra.as_view(), name='editarOrdenesDeCompra'),
    #----------------------------- Facturas --------------------------------------------------
    path('facturasCompra/', views.FacturasCompra.as_view(), name='facturasCompra'),
    path('crearFacturasCompra/', views.CrearFacturasCompra.as_view(), name='crearFacturasCompra'),
    path('editarFacturasCompra/', views.EditarFacturasCompra.as_view(), name='editarFacturasCompra'),

    #----------------------------- Ventas --------------------------------------
    path('venta/', views.Venta.as_view(), name='venta'),
    path('crearVenta/', views.CrearVenta.as_view(), name='crearVenta'),
    path('editarVenta/', views.EditarVenta.as_view(), name='editarVenta'),
    #----------------------------- Cotizaciones --------------------------------------------------
    path('cotizacionesVenta/', views.CotizacionesVenta.as_view(), name='cotizacionesVenta'),
    path('crearCotizacionesVenta/', views.CrearCotizacionesVenta.as_view(), name='crearCotizacionesVenta'),
    path('editarCotizacionesVenta/', views.EditarCotizacionesVenta.as_view(), name='editarCotizacionesVenta'),
    #----------------------------- Ordenes de Venta --------------------------------------------------
    path('ordenesDeVenta/', views.OrdenesDeVenta.as_view(), name='ordenesDeVenta'),
    path('crearOrdenesDeVenta/', views.CrearOrdenesDeVenta.as_view(), name='crearOrdenesDeVenta'),
    path('editarOrdenesDeVenta/', views.EditarOrdenesDeVenta.as_view(), name='editarOrdenesDeVenta'),
    #----------------------------- Facturas --------------------------------------------------
    path('facturasVenta/', views.FacturasVenta.as_view(), name='facturasVenta'),
    path('crearFacturasVenta/', views.CrearFacturasVenta.as_view(), name='crearFacturasVenta'),
    path('editarFacturasVenta/', views.EditarFacturasVenta.as_view(), name='editarFacturasVenta'),
    
    #----------------------------- Proveedores --------------------------------------
    path('proveedor/', views.Proveedor.as_view(), name='proveedor'),
    path('crearProveedor/', views.CrearProveedor.as_view(), name='crearProveedor'),
    path('editarProveedor/', views.EditarProveedor.as_view(), name='editarProveedor'),
    #----------------------------- Impuestos --------------------------------------
    path('impuestos/', views.Impuestos.as_view(), name='impuestos'),
    path('crearImpuestos/', views.CrearImpuestos.as_view(), name='crearImpuestos'),
    path('editarImpuestos/', views.EditarImpuestos.as_view(), name='editarImpuestos'),
    #----------------------------- Flujo de Caja --------------------------------------
    path('flujoDeCaja/', views.FlujoDeCaja.as_view(), name='flujoDeCaja'),
    path('crearFlujoDeCaja/', views.CrearFlujoDeCaja.as_view(), name='crearFlujoDeCaja'),
    path('editarFlujoDeCaja/', views.EditarFlujoDeCaja.as_view(), name='editarFlujoDeCaja'),

        #----------------------------- Contabilidad --------------------------------------
    path('cuentasContables/', views.CuentasContables.as_view(), name='cuentasContables'),
    path('crearCuentasContables/', views.CrearCuentasContables.as_view(), name='crearCuentasContables'),
    path('editarCuentasContables/', views.EditarCuentasContables.as_view(), name='editarCuentasContables'),


]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path("admin/", admin.site.urls),
    path("", include('admin_corporate.urls')),
    path("rh/empleados/", include("apps.rh.empleado.urls")),
    path("rh/remuneraciones/", include("apps.rh.remuneraciones.urls")),
    path("rh/contrataciones/", include("apps.rh.contrataciones.urls")),
    path("rh/postulaciones/", include("apps.rh.postulaciones.urls")),
    path("rh/desvinculaciones/", include("apps.rh.desvinculaciones.urls")),
    path("rh/capacitaciones/", include("apps.rh.capacitaciones.urls")),
    path("rh/evaluaciones/", include("apps.rh.evaluaciones.urls")),
    path("rh/horario/", include("apps.rh.horario.urls")),
]

apps/finanzas/views.py
from django.shortcuts import render

from django.views.generic import ListView, TemplateView, CreateView

# Create your views here.


#ListView
class Departamentos(TemplateView):
    # model = MODEL_NAME
    template_name = "pages/finanzas/departamentos/departamentos.html"

    # def get_queryset(self):
    #     queryset = super(model, self).get_queryset()
    #     queryset = queryset.
    #     return queryset


#------------------------ Vista de Centro de Costos con CRUD ------------------------------

#ListView
class CentroDeCostos(TemplateView):
    template_name = "pages/finanzas/centro-de-costos/centroDeCostos.html"


#CreateView
class CrearCentroDeCostos(TemplateView):
    template_name = "pages/finanzas/centro-de-costos/crearCentroDeCostos.html"

#UpdateView
class EditarCentroDeCostos(TemplateView):
    template_name = "pages/finanzas/centro-de-costos/editarCentroDeCostos.html"



#------------------------------------------------------------------------------------------
    

#------------------------------- Vista de Proyectos con CRUD ------------------------------

#ListView
class Proyectos(TemplateView):
    template_name = "pages/finanzas/proyectos/proyectos.html"


#CreateView
class CrearProyectos(TemplateView):
    template_name = "pages/finanzas/proyectos/crearProyectos.html"

#UpdateView
class EditarProyectos(TemplateView):
    template_name = "pages/finanzas/proyectos/editarProyectos.html"



#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Presupuestos de Centro de Costos con CRUD ------------------------------
    
#ListView
class PresupuestosCDC(TemplateView):
    template_name = "pages/finanzas/presupuestos/centro-de-costos/presupuestos.html"


#CreateView
class CrearPresupuestosCDC(TemplateView):
    template_name = "pages/finanzas/presupuestos/centro-de-costos/crearPresupuestos.html"

#UpdateView
class EditarPresupuestosCDC(TemplateView):
    template_name = "pages/finanzas/presupuestos/centro-de-costos/editarPresupuestos.html"

#------------------------------------------------------------------------------------------

#---------------------------- Vista de Presupuestos de Proyectos con CRUD ------------------------------
    
#ListView
class PresupuestosP(TemplateView):
    template_name = "pages/finanzas/presupuestos/proyectos/presupuestos.html"


#CreateView
class CrearPresupuestosP(TemplateView):
    template_name = "pages/finanzas/presupuestos/proyectos/crearPresupuestos.html"

#UpdateView
class EditarPresupuestosP(TemplateView):
    template_name = "pages/finanzas/presupuestos/proyectos/editarPresupuestos.html"



#------------------------------------------------------------------------------------------
    

#---------------------------- Vista de Compras con CRUD ------------------------------
    
#ListView
class Compra(TemplateView):
    template_name = "pages/finanzas/compra/compra.html"


#CreateView
class CrearCompra(TemplateView):
    template_name = "pages/finanzas/compra/crearCompra.html"

#UpdateView
class EditarCompra(TemplateView):
    template_name = "pages/finanzas/compra/editarCompra.html"

#------------------------------------------------------------------------------------------
    

#---------------------------- Vista de Cotizaciones de Compra con CRUD ------------------------------
    

#ListView
class CotizacionesCompra(TemplateView):
    template_name = "pages/finanzas/compra/cotizaciones/cotizaciones.html"


#CreateView
class CrearCotizacionesCompra(TemplateView):
    template_name = "pages/finanzas/compra/cotizaciones/crearCotizaciones.html"

#UpdateView
class EditarCotizacionesCompra(TemplateView):
    template_name = "pages/finanzas/compra/cotizaciones/editarCotizaciones.html"
    

#------------------------------------------------------------------------------------------
    

#---------------------------- Vista de Ordenes de Compra con CRUD ------------------------------
    
#ListView
class OrdenesDeCompra(TemplateView):
    template_name = "pages/finanzas/compra/OrdenesDeCompra/ordenesDeCompra.html"


#CreateView
class CrearOrdenesDeCompra(TemplateView):
    template_name = "pages/finanzas/compra/OrdenesDeCompra/crearOrdenesDeCompra.html"

#UpdateView
class EditarOrdenesDeCompra(TemplateView):
    template_name = "pages/finanzas/compra/OrdenesDeCompra/editarOrdenesDeCompra.html"

#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Cotizaciones de Compra con CRUD ------------------------------
    

#ListView
class FacturasCompra(TemplateView):
    template_name = "pages/finanzas/compra/facturas/facturas.html"

#CreateView
class CrearFacturasCompra(TemplateView):
    template_name = "pages/finanzas/compra/facturas/crearFactura.html"

#UpdateView
class EditarFacturasCompra(TemplateView):
    template_name = "pages/finanzas/compra/facturas/editarFactura.html"


#------------------------------------------------------------------------------------------
    
    
#---------------------------- Vista de Ventas con CRUD ------------------------------
    
#ListView
class Venta(TemplateView):
    template_name = "pages/finanzas/venta/venta.html"

#CreateView
class CrearVenta(TemplateView):
    template_name = "pages/finanzas/venta/crearVenta.html"

#UpdateView
class EditarVenta(TemplateView):
    template_name = "pages/finanzas/venta/editarVenta.html"

#------------------------------------------------------------------------------------------

#---------------------------- Vista de Cotizaciones de Venta con CRUD ------------------------------
    

#ListView
class CotizacionesVenta(TemplateView):
    template_name = "pages/finanzas/venta/cotizaciones/cotizaciones.html"


#CreateView
class CrearCotizacionesVenta(TemplateView):
    template_name = "pages/finanzas/venta/cotizaciones/crearCotizaciones.html"

#UpdateView
class EditarCotizacionesVenta(TemplateView):
    template_name = "pages/finanzas/venta/cotizaciones/editarCotizaciones.html"


#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Ordenes de Venta con CRUD ------------------------------
    
#ListView
class OrdenesDeVenta(TemplateView):
    template_name = "pages/finanzas/venta/OrdenesDeVenta/ordenesDeVenta.html"


#CreateView
class CrearOrdenesDeVenta(TemplateView):
    template_name = "pages/finanzas/venta/OrdenesDeVenta/crearOrdenesDeVenta.html"

#UpdateView
class EditarOrdenesDeVenta(TemplateView):
    template_name = "pages/finanzas/venta/OrdenesDeVenta/editarOrdenesDeVenta.html"

#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Cotizaciones de Venta con CRUD ------------------------------
    

#ListView
class FacturasVenta(TemplateView):
    template_name = "pages/finanzas/venta/facturas/facturas.html"

#CreateView
class CrearFacturasVenta(TemplateView):
    template_name = "pages/finanzas/venta/facturas/crearFactura.html"

#UpdateView
class EditarFacturasVenta(TemplateView):
    template_name = "pages/finanzas/venta/facturas/editarFactura.html"


#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Proveedores con CRUD ------------------------------
    
class Proveedor(TemplateView):
    template_name = "pages/finanzas/proveedores/proveedores.html"

#CreateView
class CrearProveedor(TemplateView):
    template_name = "pages/finanzas/proveedores/crearProveedores.html"

#UpdateView
class EditarProveedor(TemplateView):
    template_name = "pages/finanzas/proveedores/editarProveedores.html"

#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Impuestos con CRUD ------------------------------
    
class Impuestos(TemplateView):
    template_name = "pages/finanzas/impuestos/impuestos.html"

#CreateView
class CrearImpuestos(TemplateView):
    template_name = "pages/finanzas/impuestos/crearImpuestos.html"

#UpdateView
class EditarImpuestos(TemplateView):
    template_name = "pages/finanzas/impuestos/editarImpuestos.html"

#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Flujo de Caja con CRUD ------------------------------
    
class FlujoDeCaja(TemplateView):
    template_name = "pages/finanzas/flujo-de-caja/flujoDeCaja.html"

#CreateView
class CrearFlujoDeCaja(TemplateView):
    template_name = "pages/finanzas/flujo-de-caja/crearFlujoDeCaja.html"

#UpdateView
class EditarFlujoDeCaja(TemplateView):
    template_name = "pages/finanzas/flujo-de-caja/editarFlujoDeCaja.html"


#---------------------------- Vista de Contabilidad ------------------------------
    

#ListView
class CuentasContables(TemplateView):
    template_name = "pages/finanzas/contabilidad/cuentasContables/cuentasContables.html"

#CreateView
class CrearCuentasContables(TemplateView):
    template_name = "pages/finanzas/contabilidad/cuentasContables/crearCuentasContables.html"

#UpdateView
class EditarCuentasContables(TemplateView):
    template_name = "pages/finanzas/contabilidad/cuentasContables/editarCuentasContables.html"

templates/pages/finanzas/centro-de-costos/crearCentroDeCostos.html
{% extends 'layouts/base.html' %}


{% block content %}
    {% block header %}
        <header>
            <h3 class="text-center my-5">Crear Centro de Costos</h3>
        </header>

    {% endblock header %}

    <div class="container my-5 w-lg-50">
        <a class="btn bg-dark rounded" href="{% url 'app_finanzas:centroDeCostos' %}">
            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="#fff" d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/>
            </svg>
        </a>
    </div>

    <div class="container">
        <div class="card w-lg-70 w-xl-50 mx-lg-auto">
            <div class="card-body">
                <form class="p-3" action="">
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Departamento:</label>
                        <input id="formInput" class="form-control" type="text" list="lista" placeholder="Departamento ...">
                        <datalist class="d-none" id="lista">
                            <option value="departamento 1"></option>
                            <option value="departamento 2"></option>
                            <option value="departamento 3"></option>
                        </datalist>
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="CDC">Centro de Costos:</label>
                        <input id="CDC" class="form-control" type="text" placeholder="Nombre ...">
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="Código">Código del Centro de Costos:</label>
                        <input id="Código" class="form-control" type="text" placeholder="123 ...">
                    </div>
                    <div class="d-flex justify-content-center flex-wrap">
                        <button type="button" class="btn btn-primary mx-1" data-bs-toggle="modal" data-bs-target="#modalCrear">Crear</button>
                        <a class="btn btn-secondary mx-1" href="{% url 'app_finanzas:centroDeCostos' %}">Cancelar</a>
                    </div>
                </form>
            </div>
          </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modalCrear" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalCrearLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalCrearLabel">Antes de Crear un Centro de Costos</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            <div>
                <p>Se creara un nuevo registro como centro de costos, si no esta seguro cierre esta ventana</p>
            </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            <a class="btn btn-primary" href="{% url 'app_finanzas:centroDeCostos' %}">Confirmar</a>
            </div>
        </div>
        </div>
    </div>

{% endblock content %}
    

templates/pages/finanzas/centro-de-costos/editarCentroDeCostos.html
{% extends 'layouts/base.html' %}


{% block content %}
    {% block header %}
        <header>
            <h3 class="text-center my-5">Actualizar Centro de Costos</h3>
        </header>

    {% endblock header %}

    <div class="container my-5 w-lg-50">
        <a class="btn bg-dark rounded" href="{% url 'app_finanzas:centroDeCostos' %}">
            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="#fff" d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/>
            </svg>
        </a>
    </div>

    <div class="container my-5">
        <div class="card w-lg-50 mx-lg-auto">
            <div class="card-body">
                <form action="">
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Departamento:</label>
                        <input id="formInput" class="form-control" type="text" list="lista" placeholder="Departamento ...">
                        <datalist class="d-none" id="lista">
                            <option value="1"></option>
                            <option value="2"></option>
                            <option value="3"></option>
                        </datalist>
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Centro de Costos:</label>
                        <input id="formInput" class="form-control" type="text" placeholder="Nombre ...">
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Código del Centro de Costos:</label>
                        <input id="formInput" class="form-control" type="text" placeholder="123 ...">
                    </div>
                    <div class="d-flex justify-content-center flex-wrap">
                        <button type="button" class="btn btn-primary mx-1" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Actualizar</button>
                        <a href="{% url 'app_finanzas:centroDeCostos' %}" class="btn btn-secondary mx-1">Cancelar</a>
                    </div>
                </form>
            </div>
          </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="staticBackdropLabel">Antes de Actualizar</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Los cambios seran realizados al centro de costos actual, en caso de no estar seguro cierre esta ventana.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              <a type="button" class="btn btn-primary" href="{% url 'app_finanzas:centroDeCostos' %}">Actualizar</a>
            </div>
          </div>
        </div>
    </div>

{% endblock content %}
    