apps/finanzas/urls.py
from django.urls import path

from . import views

app_name = "app_finanzas"

urlpatterns = [
    #----------------------------- Departamentos ---------------------------
    path('departamentos/', views.Departamentos.as_view(), name='departamentos'),

    #---------------------------- Centro de Costos ----------------------
    path('centroDeCostos/', views.CentroDeCostos.as_view(), name='centroDeCostos'),
    path('crearCentroDeCostos/', views.CrearCentroDeCostos.as_view(), name='crearCentroDeCostos'),
    path('editarCentroDeCostos/', views.EditarCentroDeCostos.as_view(), name='editarCentroDeCostos'),
    #---------------------------- Proyectos ---------------------------
    path('proyectos/', views.Proyectos.as_view(), name='proyectos'),
    path('crearProyectos/', views.CrearProyectos.as_view(), name='crearProyectos'),
    path('editarProyectos/', views.EditarProyectos.as_view(), name='editarProyectos'),
    #----------------------------- Presupuestos de Centro de Costos -------------------------------
    path('presupuestosCDC/', views.PresupuestosCDC.as_view(), name='presupuestosCDC'),
    path('crearPresupuestosCDC/', views.CrearPresupuestosCDC.as_view(), name='crearPresupuestosCDC'),
    path('editarPresupuestosCDC/', views.EditarPresupuestosCDC.as_view(), name='editarPresupuestosCDC'),
    #----------------------------- Presupuestos de Proyectos --------------------------------------
    path('presupuestosP/', views.PresupuestosP.as_view(), name='presupuestosP'),
    path('crearPresupuestosP/', views.CrearPresupuestosP.as_view(), name='crearPresupuestosP'),
    path('editarPresupuestosP/', views.EditarPresupuestosP.as_view(), name='editarPresupuestosP'),

    #----------------------------- Compras --------------------------------------------------
    path('compra/', views.Compra.as_view(), name='compra'),
    path('crearCompra/', views.CrearCompra.as_view(), name='crearCompra'),
    path('editarCompra/', views.EditarCompra.as_view(), name='editarCompra'),
    #----------------------------- Cotizaciones --------------------------------------------------
    path('cotizacionesCompra/', views.CotizacionesCompra.as_view(), name='cotizacionesCompra'),
    path('crearCotizacionesCompra/', views.CrearCotizacionesCompra.as_view(), name='crearCotizacionesCompra'),
    path('editarCotizacionesCompra/', views.EditarCotizacionesCompra.as_view(), name='editarCotizacionesCompra'),
    #----------------------------- Ordenes de Compra --------------------------------------------------
    path('ordenesDeCompra/', views.OrdenesDeCompra.as_view(), name='ordenesDeCompra'),
    path('crearOrdenesDeCompra/', views.CrearOrdenesDeCompra.as_view(), name='crearOrdenesDeCompra'),
    path('editarOrdenesDeCompra/', views.EditarOrdenesDeCompra.as_view(), name='editarOrdenesDeCompra'),
    #----------------------------- Facturas --------------------------------------------------
    path('facturasCompra/', views.FacturasCompra.as_view(), name='facturasCompra'),
    path('crearFacturasCompra/', views.CrearFacturasCompra.as_view(), name='crearFacturasCompra'),
    path('editarFacturasCompra/', views.EditarFacturasCompra.as_view(), name='editarFacturasCompra'),

    #----------------------------- Ventas --------------------------------------
    path('venta/', views.Venta.as_view(), name='venta'),
    path('crearVenta/', views.CrearVenta.as_view(), name='crearVenta'),
    path('editarVenta/', views.EditarVenta.as_view(), name='editarVenta'),
    #----------------------------- Cotizaciones --------------------------------------------------
    path('cotizacionesVenta/', views.CotizacionesVenta.as_view(), name='cotizacionesVenta'),
    path('crearCotizacionesVenta/', views.CrearCotizacionesVenta.as_view(), name='crearCotizacionesVenta'),
    path('editarCotizacionesVenta/', views.EditarCotizacionesVenta.as_view(), name='editarCotizacionesVenta'),
    #----------------------------- Ordenes de Venta --------------------------------------------------
    path('ordenesDeVenta/', views.OrdenesDeVenta.as_view(), name='ordenesDeVenta'),
    path('crearOrdenesDeVenta/', views.CrearOrdenesDeVenta.as_view(), name='crearOrdenesDeVenta'),
    path('editarOrdenesDeVenta/', views.EditarOrdenesDeVenta.as_view(), name='editarOrdenesDeVenta'),
    #----------------------------- Facturas --------------------------------------------------
    path('facturasVenta/', views.FacturasVenta.as_view(), name='facturasVenta'),
    path('crearFacturasVenta/', views.CrearFacturasVenta.as_view(), name='crearFacturasVenta'),
    path('editarFacturasVenta/', views.EditarFacturasVenta.as_view(), name='editarFacturasVenta'),
    
    #----------------------------- Proveedores --------------------------------------
    path('proveedor/', views.Proveedor.as_view(), name='proveedor'),
    path('crearProveedor/', views.CrearProveedor.as_view(), name='crearProveedor'),
    path('editarProveedor/', views.EditarProveedor.as_view(), name='editarProveedor'),
    #----------------------------- Impuestos --------------------------------------
    path('impuestos/', views.Impuestos.as_view(), name='impuestos'),
    path('crearImpuestos/', views.CrearImpuestos.as_view(), name='crearImpuestos'),
    path('editarImpuestos/', views.EditarImpuestos.as_view(), name='editarImpuestos'),
    #----------------------------- Flujo de Caja --------------------------------------
    path('flujoDeCaja/', views.FlujoDeCaja.as_view(), name='flujoDeCaja'),
    path('crearFlujoDeCaja/', views.CrearFlujoDeCaja.as_view(), name='crearFlujoDeCaja'),
    path('editarFlujoDeCaja/', views.EditarFlujoDeCaja.as_view(), name='editarFlujoDeCaja'),

        #----------------------------- Contabilidad --------------------------------------
    path('cuentasContables/', views.CuentasContables.as_view(), name='cuentasContables'),
    path('crearCuentasContables/', views.CrearCuentasContables.as_view(), name='crearCuentasContables'),
    path('editarCuentasContables/', views.EditarCuentasContables.as_view(), name='editarCuentasContables'),


]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path("admin/", admin.site.urls),
    path("", include('admin_corporate.urls')),
    path("rh/empleados/", include("apps.rh.empleado.urls")),
    path("rh/remuneraciones/", include("apps.rh.remuneraciones.urls")),
    path("rh/contrataciones/", include("apps.rh.contrataciones.urls")),
    path("rh/postulaciones/", include("apps.rh.postulaciones.urls")),
    path("rh/desvinculaciones/", include("apps.rh.desvinculaciones.urls")),
    path("rh/capacitaciones/", include("apps.rh.capacitaciones.urls")),
    path("rh/evaluaciones/", include("apps.rh.evaluaciones.urls")),
    path("rh/horario/", include("apps.rh.horario.urls")),
]

apps/finanzas/views.py
from django.shortcuts import render

from django.views.generic import ListView, TemplateView, CreateView

# Create your views here.


#ListView
class Departamentos(TemplateView):
    # model = MODEL_NAME
    template_name = "pages/finanzas/departamentos/departamentos.html"

    # def get_queryset(self):
    #     queryset = super(model, self).get_queryset()
    #     queryset = queryset.
    #     return queryset


#------------------------ Vista de Centro de Costos con CRUD ------------------------------

#ListView
class CentroDeCostos(TemplateView):
    template_name = "pages/finanzas/centro-de-costos/centroDeCostos.html"


#CreateView
class CrearCentroDeCostos(TemplateView):
    template_name = "pages/finanzas/centro-de-costos/crearCentroDeCostos.html"

#UpdateView
class EditarCentroDeCostos(TemplateView):
    template_name = "pages/finanzas/centro-de-costos/editarCentroDeCostos.html"



#------------------------------------------------------------------------------------------
    

#------------------------------- Vista de Proyectos con CRUD ------------------------------

#ListView
class Proyectos(TemplateView):
    template_name = "pages/finanzas/proyectos/proyectos.html"


#CreateView
class CrearProyectos(TemplateView):
    template_name = "pages/finanzas/proyectos/crearProyectos.html"

#UpdateView
class EditarProyectos(TemplateView):
    template_name = "pages/finanzas/proyectos/editarProyectos.html"



#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Presupuestos de Centro de Costos con CRUD ------------------------------
    
#ListView
class PresupuestosCDC(TemplateView):
    template_name = "pages/finanzas/presupuestos/centro-de-costos/presupuestos.html"


#CreateView
class CrearPresupuestosCDC(TemplateView):
    template_name = "pages/finanzas/presupuestos/centro-de-costos/crearPresupuestos.html"

#UpdateView
class EditarPresupuestosCDC(TemplateView):
    template_name = "pages/finanzas/presupuestos/centro-de-costos/editarPresupuestos.html"

#------------------------------------------------------------------------------------------

#---------------------------- Vista de Presupuestos de Proyectos con CRUD ------------------------------
    
#ListView
class PresupuestosP(TemplateView):
    template_name = "pages/finanzas/presupuestos/proyectos/presupuestos.html"


#CreateView
class CrearPresupuestosP(TemplateView):
    template_name = "pages/finanzas/presupuestos/proyectos/crearPresupuestos.html"

#UpdateView
class EditarPresupuestosP(TemplateView):
    template_name = "pages/finanzas/presupuestos/proyectos/editarPresupuestos.html"



#------------------------------------------------------------------------------------------
    

#---------------------------- Vista de Compras con CRUD ------------------------------
    
#ListView
class Compra(TemplateView):
    template_name = "pages/finanzas/compra/compra.html"


#CreateView
class CrearCompra(TemplateView):
    template_name = "pages/finanzas/compra/crearCompra.html"

#UpdateView
class EditarCompra(TemplateView):
    template_name = "pages/finanzas/compra/editarCompra.html"

#------------------------------------------------------------------------------------------
    

#---------------------------- Vista de Cotizaciones de Compra con CRUD ------------------------------
    

#ListView
class CotizacionesCompra(TemplateView):
    template_name = "pages/finanzas/compra/cotizaciones/cotizaciones.html"


#CreateView
class CrearCotizacionesCompra(TemplateView):
    template_name = "pages/finanzas/compra/cotizaciones/crearCotizaciones.html"

#UpdateView
class EditarCotizacionesCompra(TemplateView):
    template_name = "pages/finanzas/compra/cotizaciones/editarCotizaciones.html"
    

#------------------------------------------------------------------------------------------
    

#---------------------------- Vista de Ordenes de Compra con CRUD ------------------------------
    
#ListView
class OrdenesDeCompra(TemplateView):
    template_name = "pages/finanzas/compra/OrdenesDeCompra/ordenesDeCompra.html"


#CreateView
class CrearOrdenesDeCompra(TemplateView):
    template_name = "pages/finanzas/compra/OrdenesDeCompra/crearOrdenesDeCompra.html"

#UpdateView
class EditarOrdenesDeCompra(TemplateView):
    template_name = "pages/finanzas/compra/OrdenesDeCompra/editarOrdenesDeCompra.html"

#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Cotizaciones de Compra con CRUD ------------------------------
    

#ListView
class FacturasCompra(TemplateView):
    template_name = "pages/finanzas/compra/facturas/facturas.html"

#CreateView
class CrearFacturasCompra(TemplateView):
    template_name = "pages/finanzas/compra/facturas/crearFactura.html"

#UpdateView
class EditarFacturasCompra(TemplateView):
    template_name = "pages/finanzas/compra/facturas/editarFactura.html"


#------------------------------------------------------------------------------------------
    
    
#---------------------------- Vista de Ventas con CRUD ------------------------------
    
#ListView
class Venta(TemplateView):
    template_name = "pages/finanzas/venta/venta.html"

#CreateView
class CrearVenta(TemplateView):
    template_name = "pages/finanzas/venta/crearVenta.html"

#UpdateView
class EditarVenta(TemplateView):
    template_name = "pages/finanzas/venta/editarVenta.html"

#------------------------------------------------------------------------------------------

#---------------------------- Vista de Cotizaciones de Venta con CRUD ------------------------------
    

#ListView
class CotizacionesVenta(TemplateView):
    template_name = "pages/finanzas/venta/cotizaciones/cotizaciones.html"


#CreateView
class CrearCotizacionesVenta(TemplateView):
    template_name = "pages/finanzas/venta/cotizaciones/crearCotizaciones.html"

#UpdateView
class EditarCotizacionesVenta(TemplateView):
    template_name = "pages/finanzas/venta/cotizaciones/editarCotizaciones.html"


#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Ordenes de Venta con CRUD ------------------------------
    
#ListView
class OrdenesDeVenta(TemplateView):
    template_name = "pages/finanzas/venta/OrdenesDeVenta/ordenesDeVenta.html"


#CreateView
class CrearOrdenesDeVenta(TemplateView):
    template_name = "pages/finanzas/venta/OrdenesDeVenta/crearOrdenesDeVenta.html"

#UpdateView
class EditarOrdenesDeVenta(TemplateView):
    template_name = "pages/finanzas/venta/OrdenesDeVenta/editarOrdenesDeVenta.html"

#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Cotizaciones de Venta con CRUD ------------------------------
    

#ListView
class FacturasVenta(TemplateView):
    template_name = "pages/finanzas/venta/facturas/facturas.html"

#CreateView
class CrearFacturasVenta(TemplateView):
    template_name = "pages/finanzas/venta/facturas/crearFactura.html"

#UpdateView
class EditarFacturasVenta(TemplateView):
    template_name = "pages/finanzas/venta/facturas/editarFactura.html"


#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Proveedores con CRUD ------------------------------
    
class Proveedor(TemplateView):
    template_name = "pages/finanzas/proveedores/proveedores.html"

#CreateView
class CrearProveedor(TemplateView):
    template_name = "pages/finanzas/proveedores/crearProveedores.html"

#UpdateView
class EditarProveedor(TemplateView):
    template_name = "pages/finanzas/proveedores/editarProveedores.html"

#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Impuestos con CRUD ------------------------------
    
class Impuestos(TemplateView):
    template_name = "pages/finanzas/impuestos/impuestos.html"

#CreateView
class CrearImpuestos(TemplateView):
    template_name = "pages/finanzas/impuestos/crearImpuestos.html"

#UpdateView
class EditarImpuestos(TemplateView):
    template_name = "pages/finanzas/impuestos/editarImpuestos.html"

#------------------------------------------------------------------------------------------
    
#---------------------------- Vista de Flujo de Caja con CRUD ------------------------------
    
class FlujoDeCaja(TemplateView):
    template_name = "pages/finanzas/flujo-de-caja/flujoDeCaja.html"

#CreateView
class CrearFlujoDeCaja(TemplateView):
    template_name = "pages/finanzas/flujo-de-caja/crearFlujoDeCaja.html"

#UpdateView
class EditarFlujoDeCaja(TemplateView):
    template_name = "pages/finanzas/flujo-de-caja/editarFlujoDeCaja.html"


#---------------------------- Vista de Contabilidad ------------------------------
    

#ListView
class CuentasContables(TemplateView):
    template_name = "pages/finanzas/contabilidad/cuentasContables/cuentasContables.html"

#CreateView
class CrearCuentasContables(TemplateView):
    template_name = "pages/finanzas/contabilidad/cuentasContables/crearCuentasContables.html"

#UpdateView
class EditarCuentasContables(TemplateView):
    template_name = "pages/finanzas/contabilidad/cuentasContables/editarCuentasContables.html"

templates/pages/finanzas/impuestos/impuestos.html
{% extends 'layouts/base.html' %} {% load static %} {% block content %}
<div class="container-fluid py-4 px-5">
  <div class="row">
    <div class="col-12">
      <h3 >Impuestos</h3>
      <hr>
      <br>
      <div class="card border shadow-xs mb-4">
        <div class="card-header border-bottom pb-0">
          <div class="d-sm-flex align-items-center mb-3">
            <div>
              <h6 class="font-weight-semibold text-lg mb-0">Listado de impuestos</h6>
            </div>
            <div class="ms-auto d-flex flex-md-row flex-column">
              <div class="input-group input-group-sm ms-auto me-2">
                <span class="input-group-text text-body">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"></path>
                  </svg>
                </span>
                <input type="text" class="form-control form-control-sm" placeholder="Buscar">
              </div>
                <a href="{% url 'app_finanzas:crearImpuestos' %}"  class="btn btn-sm btn-dark btn-icon d-flex align-items-center mb-0 me-2">
                  <span class="btn-inner--icon" >
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill d-block me-2" viewBox="0 0 16 16">
                      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"/>
                    </svg>
                  </span>
                  <span class="btn-inner--text">Impuesto</span>
                </a>
              <a data-bs-toggle="modal" data-bs-target="#" type="button"  class="btn btn-sm btn-dark btn-icon d-flex align-items-center mb-0 me-2">
                <span class="btn-inner--icon">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill d-block me-2" viewBox="0 0 512 512">
                    <path d="M288 32c0-17.7-14.3-32-32-32s-32 14.3-32 32V274.7l-73.4-73.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l128 128c12.5 12.5 32.8 12.5 45.3 0l128-128c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L288 274.7V32zM64 352c-35.3 0-64 28.7-64 64v32c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V416c0-35.3-28.7-64-64-64H346.5l-45.3 45.3c-25 25-65.5 25-90.5 0L165.5 352H64zm368 56a24 24 0 1 1 0 48 24 24 0 1 1 0-48z"/>
                  </svg>
                </span>
                <span class="btn-inner--text">Exportar</span>
              </a>
              <a data-bs-toggle="modal" data-bs-target="#" type="button"  class="btn btn-sm btn-dark btn-icon d-flex align-items-center mb-0 me-2">
                <span class="btn-inner--icon">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill d-block me-2" viewBox="0 0 512 512">
                    <path d="M128 0C92.7 0 64 28.7 64 64v96h64V64H354.7L384 93.3V160h64V93.3c0-17-6.7-33.3-18.7-45.3L400 18.7C388 6.7 371.7 0 354.7 0H128zM384 352v32 64H128V384 368 352H384zm64 32h32c17.7 0 32-14.3 32-32V256c0-35.3-28.7-64-64-64H64c-35.3 0-64 28.7-64 64v96c0 17.7 14.3 32 32 32H64v64c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V384zM432 248a24 24 0 1 1 0 48 24 24 0 1 1 0-48z"/>
                  </svg>
                </span>
                <span class="btn-inner--text">Imprimir</span>
              </a>
            </div>
          </div>
        </div>
        <div class="card-body px-0 py-0">
          <div class="table-responsive p-0">
            <table class="table align-items-center  table-bordered table-hover justify-content-center mb-0">
              <thead class="bg-gray-100">
                <tr>
                  <th class="text-secondary text-xs font-weight-bold ps-2">Nombre Impuesto</th>
                  <th class="text-secondary text-xs font-weight-bold ps-2">Tipo de Impuesto</th>
                  <th class="text-secondary text-xs font-weight-bold ps-2">Impuesto</th>
                  <th class="text-secondary text-xs font-weight-bold ps-2">Código</th>
                  <th class="text-secondary text-xs font-weight-bold ps-2">Acciones</th>
                </tr>
              </thead>
              <tbody> 
                <tr class="text-start">
                  <td>
                    <span class="text-sm font-weight-normal">Nombre ...</span>
                  </td>
                  <td>
                    <span class="text-sm font-weight-normal">Compra ...</span>
                  </td>
                  <td>
                    <span class="text-sm font-weight-normal">0.19</span>
                  </td>
                  <td class="">
                    <span class="text-sm font-weight-normal">123 ...</span>
                  </td>
                  <td class="align-middle">
                    <div class="d-flex justify-content-center px-4">
                      <span>
                      <a href="{% url 'app_finanzas:editarImpuestos' %}" class="text-secondary font-weight-bold text-xs" data-bs-toggle="tooltip" data-bs-title="Editar Impuesto">
                        <svg width="14" height="14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                          <path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.7 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160V416c0 53 43 96 96 96H352c53 0 96-43 96-96V320c0-17.7-14.3-32-32-32s-32 14.3-32 32v96c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h96c17.7 0 32-14.3 32-32s-14.3-32-32-32H96z" fill="#64748B"/>
                      </svg>
                    </a>
                  </span>
                    <span data-bs-toggle="modal" data-bs-target="#modalEliminarImpuesto">
                        <a type="button" class="text-secondary font-weight-bold text-xs" data-bs-toggle="tooltip" data-bs-title="Eliminar Impuesto">
                          <svg width="14" height="14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                            <path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z" fill="#64748B"/>
                          </svg>
                        </a>
                    </span>
                  </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="border-top py-3 px-3 d-flex align-items-center">
            <button class="btn btn-sm btn-white d-sm-block d-none mb-0">Anterior</button>
            <nav aria-label="..." class="ms-auto">
              <ul class="pagination pagination-light mb-0">
                <li class="page-item active" aria-current="page">
                  <span class="page-link font-weight-bold">1</span>
                </li>
                <li class="page-item"><a class="page-link border-0 font-weight-bold" href="javascript:;">2</a></li>
                <li class="page-item"><a class="page-link border-0 font-weight-bold d-sm-inline-flex d-none" href="javascript:;">3</a></li>
                <li class="page-item"><a class="page-link border-0 font-weight-bold" href="javascript:;">...</a></li>
                <li class="page-item"><a class="page-link border-0 font-weight-bold d-sm-inline-flex d-none" href="javascript:;">8</a></li>
                <li class="page-item"><a class="page-link border-0 font-weight-bold" href="javascript:;">9</a></li>
                <li class="page-item"><a class="page-link border-0 font-weight-bold" href="javascript:;">10</a></li>
              </ul>
            </nav>
            <button class="btn btn-sm btn-white d-sm-block d-none mb-0 ms-auto">Siguiente</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="modalEliminarImpuesto" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalEliminarImpuestoLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="modalEliminarImpuestoLabel">Antes de Eliminar</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Se eliminará el registro del impuesto actual, en caso de no estar seguro cierre esta ventana.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              <a type="button" class="btn btn-primary" href="{% url 'app_finanzas:impuestos' %}">Confirmar</a>
            </div>
          </div>
        </div>
    </div>

    {% include 'includes/footer.html' %}
{% endblock content %}
    