apps/finanzas/urls.py
from django.urls import path

from . import views

app_name = "app_finanzas"

urlpatterns = [
    #----------------------------- Departamentos ---------------------------
    path('departamentos/', views.Departamentos.as_view(), name='departamentos'),

    #---------------------------- Centro de Costos ----------------------
    path('centroDeCostos/', views.CentroDeCostos.as_view(), name='centroDeCostos'),
    path('crearCentroDeCostos/', views.CrearCentroDeCostos.as_view(), name='crearCentroDeCostos'),
    path('editarCentroDeCostos/', views.EditarCentroDeCostos.as_view(), name='editarCentroDeCostos'),
    #---------------------------- Proyectos ---------------------------
    path('proyectos/', views.Proyectos.as_view(), name='proyectos'),
    path('crearProyectos/', views.CrearProyectos.as_view(), name='crearProyectos'),
    path('editarProyectos/', views.EditarProyectos.as_view(), name='editarProyectos'),
    #----------------------------- Presupuestos de Centro de Costos -------------------------------
    path('presupuestosCDC/', views.PresupuestosCDC.as_view(), name='presupuestosCDC'),
    path('crearPresupuestosCDC/', views.CrearPresupuestosCDC.as_view(), name='crearPresupuestosCDC'),
    path('editarPresupuestosCDC/', views.EditarPresupuestosCDC.as_view(), name='editarPresupuestosCDC'),
    #----------------------------- Presupuestos de Proyectos --------------------------------------
    path('presupuestosP/', views.PresupuestosP.as_view(), name='presupuestosP'),
    path('crearPresupuestosP/', views.CrearPresupuestosP.as_view(), name='crearPresupuestosP'),
    path('editarPresupuestosP/', views.EditarPresupuestosP.as_view(), name='editarPresupuestosP'),

    #----------------------------- Compras --------------------------------------------------
    path('compra/', views.Compra.as_view(), name='compra'),
    path('crearCompra/', views.CrearCompra.as_view(), name='crearCompra'),
    path('editarCompra/', views.EditarCompra.as_view(), name='editarCompra'),
    #----------------------------- Cotizaciones --------------------------------------------------
    path('cotizacionesCompra/', views.CotizacionesCompra.as_view(), name='cotizacionesCompra'),
    path('crearCotizacionesCompra/', views.CrearCotizacionesCompra.as_view(), name='crearCotizacionesCompra'),
    path('editarCotizacionesCompra/', views.EditarCotizacionesCompra.as_view(), name='editarCotizacionesCompra'),
    #----------------------------- Ordenes de Compra --------------------------------------------------
    path('ordenesDeCompra/', views.OrdenesDeCompra.as_view(), name='ordenesDeCompra'),
    path('crearOrdenesDeCompra/', views.CrearOrdenesDeCompra.as_view(), name='crearOrdenesDeCompra'),
    path('editarOrdenesDeCompra/', views.EditarOrdenesDeCompra.as_view(), name='editarOrdenesDeCompra'),
    #----------------------------- Facturas --------------------------------------------------
    path('facturasCompra/', views.FacturasCompra.as_view(), name='facturasCompra'),
    path('crearFacturasCompra/', views.CrearFacturasCompra.as_view(), name='crearFacturasCompra'),
    path('editarFacturasCompra/', views.EditarFacturasCompra.as_view(), name='editarFacturasCompra'),

    #----------------------------- Ventas --------------------------------------
    path('venta/', views.Venta.as_view(), name='venta'),
    path('crearVenta/', views.CrearVenta.as_view(), name='crearVenta'),
    path('editarVenta/', views.EditarVenta.as_view(), name='editarVenta'),
    #----------------------------- Cotizaciones --------------------------------------------------
    path('cotizacionesVenta/', views.CotizacionesVenta.as_view(), name='cotizacionesVenta'),
    path('crearCotizacionesVenta/', views.CrearCotizacionesVenta.as_view(), name='crearCotizacionesVenta'),
    path('editarCotizacionesVenta/', views.EditarCotizacionesVenta.as_view(), name='editarCotizacionesVenta'),
    #----------------------------- Ordenes de Venta --------------------------------------------------
    path('ordenesDeVenta/', views.OrdenesDeVenta.as_view(), name='ordenesDeVenta'),
    path('crearOrdenesDeVenta/', views.CrearOrdenesDeVenta.as_view(), name='crearOrdenesDeVenta'),
    path('editarOrdenesDeVenta/', views.EditarOrdenesDeVenta.as_view(), name='editarOrdenesDeVenta'),
    #----------------------------- Facturas --------------------------------------------------
    path('facturasVenta/', views.FacturasVenta.as_view(), name='facturasVenta'),
    path('crearFacturasVenta/', views.CrearFacturasVenta.as_view(), name='crearFacturasVenta'),
    path('editarFacturasVenta/', views.EditarFacturasVenta.as_view(), name='editarFacturasVenta'),
    
    #----------------------------- Proveedores --------------------------------------
    path('proveedor/', views.Proveedor.as_view(), name='proveedor'),
    path('crearProveedor/', views.CrearProveedor.as_view(), name='crearProveedor'),
    path('editarProveedor/', views.EditarProveedor.as_view(), name='editarProveedor'),
    #----------------------------- Impuestos --------------------------------------
    path('impuestos/', views.Impuestos.as_view(), name='impuestos'),
    path('crearImpuestos/', views.CrearImpuestos.as_view(), name='crearImpuestos'),
    path('editarImpuestos/', views.EditarImpuestos.as_view(), name='editarImpuestos'),
    #----------------------------- Flujo de Caja --------------------------------------
    path('flujoDeCaja/', views.FlujoDeCaja.as_view(), name='flujoDeCaja'),
    path('crearFlujoDeCaja/', views.CrearFlujoDeCaja.as_view(), name='crearFlujoDeCaja'),
    path('editarFlujoDeCaja/', views.EditarFlujoDeCaja.as_view(), name='editarFlujoDeCaja'),

        #----------------------------- Contabilidad --------------------------------------
    path('cuentasContables/', views.CuentasContables.as_view(), name='cuentasContables'),
    path('crearCuentasContables/', views.CrearCuentasContables.as_view(), name='crearCuentasContables'),
    path('editarCuentasContables/', views.EditarCuentasContables.as_view(), name='editarCuentasContables'),


]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path("admin/", admin.site.urls),
    path("", include('admin_corporate.urls')),
    path("rh/empleados/", include("apps.rh.empleado.urls")),
    path("rh/remuneraciones/", include("apps.rh.remuneraciones.urls")),
    path("rh/contrataciones/", include("apps.rh.contrataciones.urls")),
    path("rh/postulaciones/", include("apps.rh.postulaciones.urls")),
    path("rh/desvinculaciones/", include("apps.rh.desvinculaciones.urls")),
    path("rh/capacitaciones/", include("apps.rh.capacitaciones.urls")),
    path("rh/evaluaciones/", include("apps.rh.evaluaciones.urls")),
    path("rh/horario/", include("apps.rh.horario.urls")),
]

templates/pages/finanzas/presupuestos/centro-de-costos/crearPresupuestos.html
{% extends 'layouts/base.html' %}


{% block content %}
    {% block header %}
        <header>
            <h3 class="text-center my-5">Crear Presupuesto</h3>
        </header>

    {% endblock header %}

    <div class="container my-5 w-lg-75">
        <a class="btn bg-dark rounded" href="{% url 'app_finanzas:presupuestosCDC' %}">
            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="#fff" d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/>
            </svg>
        </a>
    </div>

    <div class="container">
        <div class="card w-lg-75 mx-lg-auto">
            <div class="card-body">
                <form action="">
                    <div class="container bg-dark rounded">
                        <p class="py-1 text-light font-weight-bold">Datos Presupuesto:</p>
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Departamento:</label>
                        <input id="formInput" class="form-control" type="text" list="lista" placeholder="Departamento ...">
                        <datalist class="d-none" id="lista">
                            <option value="1"></option>
                            <option value="2"></option>
                            <option value="3"></option>
                        </datalist>
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Centro de Costos:</label>
                        <input id="formInput" class="form-control" type="text" list="lista-CDC" placeholder="Centro de Costos ...">
                        <datalist class="d-none" id="lista-CDC">
                            <option value="1"></option>
                            <option value="2"></option>
                            <option value="3"></option>
                        </datalist>
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Nombre Presupuesto:</label>
                        <input id="formInput" class="form-control" type="text" placeholder="Nombre ...">
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Código Presupuesto:</label>
                        <input id="formInput" class="form-control" type="text" placeholder="123 ...">
                    </div>
                    <div class="container bg-dark rounded">
                        <p class="py-1 text-light font-weight-bold">Detalle del Presupuesto:</p>
                    </div>
                    <div class="card-body px-0 pb-0">
                        <div class="table-responsive p-0">
                          <table class="table table-hover table-bordered align-items-center justify-content-center mb-0">
                            <thead class="bg-gray-100">
                                <tr>
                                  <th class="text-secondary text-xs font-weight-bold">Código</th>
                                  <th class="text-secondary text-xs font-weight-bold ps-2">Descripción</th>
                                  <th class="text-secondary text-xs font-weight-bold ps-2">Cantidad</th>
                                  <th class="text-secondary text-xs font-weight-bold ps-2">Neto</th>
                                  <th class="text-secondary text-xs font-weight-bold ps-2">Impuesto</th>
                                  <th class="text-secondary text-xs font-weight-bold ps-2">Total</th>
                                  <th class="text-secondary text-xs font-weight-bold ps-2">Acción</th>
                                </tr>
                              </thead>
                            <tbody class="items">
                                <tr>
                                    <td class="ps-1">
                                        <input class="form-control" type="text" placeholder="123 ...">
                                    </td>
                                    <td class="ps-1">
                                        <input class="form-control descripcion" type="text" placeholder="Item ...">
                                    </td>
                                    <td class="ps-1">
                                        <input class="form-control cantidad" type="number" min="1" placeholder="2 ...">
                                    </td>
                                    <td class="ps-1">
                                        <input class="form-control neto" type="text" placeholder="00.000.000">
                                    </td>
                                    <td class="ps-1 text-center">
                                        <span class="text-sm font-weight-normal">0.19</span>
                                    </td>
                                    <td class="ps-1 text-center">
                                        <span class="text-sm font-weight-normal total"></span>
                                    </td>
                                    <td class="ps-1 text-center">
                                        <button type="button" data-bs-toggle="tooltip" data-bs-title="Eliminar Item" class="eliminar btn m-0">
                                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                                <path fill="#1e293b" d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                                            </svg>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                          </table>
                            <a id="Agregar" data-bs-toggle="tooltip" data-bs-title="Agregar Item" class="btn d-inline-block mt-3 mb-0">
                                <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                    <path fill="#1e293b" d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 344V280H168c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V168c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H280v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/>
                                </svg>
                            </a>
                            <a id="Eliminar" data-bs-toggle="tooltip" data-bs-title="Eliminar Item" class="btn d-inline-block mt-3 mb-0">
                                <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                    <path fill="#1e293b" d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                    <hr class="dotted">
                    <div class="d-flex flex-column align-items-end">
                        <p class="mt-3">Total sin Impuesto: $<span class="total-sin-impuesto">00.000.000</span></p>
                        <p class="mb-1">Con Impuesto: $<span class="total-impuesto">00.000.000</span></p>
                        <hr class="w-50 dotted">
                        <p class="font-weight-bold">Total: $<span id="totalOrden">00.000.000</span></p>
                    </div>
                    <hr class="dotted">
                    <div class="d-flex justify-content-center mt-5 flex-wrap">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Crear Presupuesto</button>
                        <a class="btn btn-secondary mx-1" href="{% url 'app_finanzas:presupuestosCDC' %}">Cancelar</a>
                    </div>
                </form>
            </div>
          </div>
    </div>

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="staticBackdropLabel">Por seguridad</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Los datos ingresados se registraran como un nuevo presupuesto, en caso de no estar seguro cierre esta ventana.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              <a type="button" class="btn btn-primary" href="{% url 'app_finanzas:presupuestosCDC' %}">Crear Presupuesto</a>
            </div>
          </div>
        </div>
    </div>

{% endblock content %}


{% block extrascripts %}
    <script src="../../../../static/js/finanzas/CentroDeCostos/presupuestos/Presupuesto.js"></script>
{% endblock extrascripts %}
    
    

templates/pages/finanzas/presupuestos/centro-de-costos/editarPresupuestos.html
{% extends 'layouts/base.html' %}


{% block content %}
    {% block header %}
        <header>
            <h3 class="text-center my-5">Actualizar Presupuesto</h3>
        </header>

    {% endblock header %}

    <div class="container my-5 w-lg-75">
        <a class="btn bg-dark rounded" href="{% url 'app_finanzas:presupuestosCDC' %}">
            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="#fff" d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/>
            </svg>
        </a>
    </div>

    <div class="container">
        <div class="card w-lg-75 mx-lg-auto">
            <div class="card-body">
                <form action="">
                    <div class="container bg-dark rounded">
                        <p class="py-1 text-light font-weight-bold">Datos Presupuesto:</p>
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Departamento:</label>
                        <input id="formInput" class="form-control" type="text" list="lista" placeholder="Departamento ...">
                        <datalist class="d-none" id="lista">
                            <option value="1"></option>
                            <option value="2"></option>
                            <option value="3"></option>
                        </datalist>
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Centro de Costos:</label>
                        <input id="formInput" class="form-control" type="text" list="lista-CDC" placeholder="Centro de Costos ...">
                        <datalist class="d-none" id="lista-CDC">
                            <option value="1"></option>
                            <option value="2"></option>
                            <option value="3"></option>
                        </datalist>
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Nombre Presupuesto:</label>
                        <input id="formInput" class="form-control" type="text" placeholder="Nombre ...">
                    </div>
                    <div class="mb-3">
                        <label for="formInput" class="form-label" for="">Código Presupuesto:</label>
                        <input id="formInput" class="form-control" type="text" placeholder="123 ...">
                    </div>
                    <div class="container bg-dark rounded">
                        <p class="py-1 text-light font-weight-bold">Lista del Presupuesto:</p>
                    </div>
                    <div class="card-body px-0 pb-0">
                        <div class="table-responsive p-0">
                            <table class="table table-hover table-bordered align-items-center justify-content-center mb-0">
                                <thead class="bg-gray-100">
                                    <tr>
                                      <th class="text-secondary text-xs font-weight-bold">Código</th>
                                      <th class="text-secondary text-xs font-weight-bold ps-2">Descripción</th>
                                      <th class="text-secondary text-xs font-weight-bold ps-2">Cantidad</th>
                                      <th class="text-secondary text-xs font-weight-bold ps-2">Neto</th>
                                      <th class="text-secondary text-xs font-weight-bold ps-2">Impuesto</th>
                                      <th class="text-secondary text-xs font-weight-bold ps-2">Total</th>
                                      <th class="text-secondary text-xs font-weight-bold ps-2">Acción</th>
                                    </tr>
                                  </thead>
                                <tbody class="items">
                                    <tr>
                                        <td class="ps-1">
                                            <input class="form-control" type="text" placeholder="123 ...">
                                        </td>
                                        <td class="ps-1">
                                            <input class="form-control descripcion" type="text" placeholder="Item ...">
                                        </td>
                                        <td class="ps-1">
                                            <input class="form-control cantidad" type="number" min="1" placeholder="2 ...">
                                        </td>
                                        <td class="ps-1">
                                            <input class="form-control neto" type="text" placeholder="00.000.000">
                                        </td>
                                        <td class="ps-1 text-center">
                                            <span class="text-sm font-weight-normal">0.19</span>
                                        </td>
                                        <td class="ps-1 text-center">
                                            <span class="text-sm font-weight-normal total"></span>
                                        </td>
                                        <td class="ps-1 text-center">
                                            <button type="button" data-bs-toggle="tooltip" data-bs-title="Eliminar Item" class="eliminar btn m-0">
                                                <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                                    <path fill="#1e293b" d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                                                </svg>
                                            </button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <a id="Agregar" data-bs-toggle="tooltip" data-bs-title="Agregar Item" class="btn d-inline-block mt-3 mb-0">
                                <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                    <path fill="#1e293b" d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 344V280H168c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V168c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H280v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/>
                                </svg>
                            </a>
                            <a id="Eliminar" data-bs-toggle="tooltip" data-bs-title="Eliminar Item" class="btn d-inline-block mt-3 mb-0">
                                <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                    <path fill="#1e293b" d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                    <hr class="dotted">
                    <div class="d-flex flex-column align-items-end">
                        <p class="mt-3">Total sin Impuesto: $<span class="total-sin-impuesto">00.000.000</span></p>
                        <p class="mb-1">Con Impuesto: $<span class="total-impuesto">00.000.000</span></p>
                        <hr class="w-50 dotted">
                        <p class="font-weight-bold">Total: $<span id="totalOrden">00.000.000</span></p>
                    </div>
                    <hr class="dotted">
                    <div class="d-flex justify-content-center flex-wrap mt-5">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Actualizar Presupuesto</button>
                        <a class="btn btn-secondary mx-1" href="{% url 'app_finanzas:presupuestosCDC' %}">Cancelar</a>
                    </div>
                </form>
            </div>
          </div>
    </div>

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="staticBackdropLabel">Antes de Actualizar</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Los cambios seran realizados al presupuesto actual, en caso de no estar seguro cierre esta ventana.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              <a type="button" class="btn btn-primary" href="{% url 'app_finanzas:presupuestosCDC' %}">Actualizar Presupuesto</a>
            </div>
          </div>
        </div>
    </div>

{% endblock content %}
    

{% block extrascripts %}
    <script src="../../../../static/js/finanzas/CentroDeCostos/presupuestos/Presupuesto.js"></script>
{% endblock extrascripts %}
    